version: "3"
services:
  backend:
    container_name: annotation-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "3000:3000"
      - "8000:8000"
      - "8002:8002"
    environment:
      - SCM_DIR=/root/scm_result
      - PROD_MODE=0
      - SERVICE_PORT=3000
    working_dir: /root/mozi_annotation_service/
    command: bash -c "circusd --log-level debug circus.ini"
    links:
      - frontend
  frontend:
    container_name: annotation-ui
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "$SERVER_PORT:3200"
    volumes:
      - ./react:/root/mozi_annotation_ui/
    environment:
      - SERVER_ADDR=$SERVER_ADDR:3001
    working_dir: /root/mozi_annotation_ui/
    command: bash -c "npm install && npm run-script build && serve -l 3200 -s build"
