version: "3"
services:
  backend:
    container_name: annotation-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3002:3002" # Web Server
      - "3001:3001" # GRPC Proxy Server
      - "3000:3000" # GRPC Server
      - "8000:8000"
      - "8002:8002"
    environment:
      - SCM_DIR=/root/scm_result
      - PROD_MODE=0
      - SERVICE_PORT=3000
      - REDIS_URI =redis://redis:6379/0
      - MONGODB_URI=mongodb://mongo:27017/
    working_dir: /root/mozi_annotation_service/
    command: bash -c "circusd --log-level debug circus.ini"
    links:
      - frontend
      - result-ui

    volumes:
      - /etc:/etc
#      - .:/root/mozi_annotation_service

  frontend:
    container_name: annotation-ui
    build:
      context: ./react
      dockerfile: Dockerfile
    environment:
      - SERVICE_ADDR=$SERVICE_ADDR
    ports:
      - "$SERVER_PORT:80"

  result-ui:
    container_name: result-ui
    build:
      context: ./annotation-result-ui
      dockerfile: Dockerfile
    environment:
      - SERVICE_ADDR=$SERVICE_ADDR
    ports:
      - "$RESULT_PORT:80"
  redis:
    image: redis

  mongo:
    image: mongo
