version: "3"
services:
  backend:
    container_name: annotation-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "3000:3000"
      - "8000:8000"
      - "8002:8002"
    environment:
      - SCM_DIR=/root/scm_result
      - PROD_MODE=0
      - SERVICE_PORT=3000
    working_dir: /root/mozi_annotation_service/
    command: bash -c "circusd --log-level debug circus.ini"
    links:
      - frontend

    volumes:
      - /etc:/etc

  frontend:
    container_name: annotation-ui
    build:
      context: ./react
      dockerfile: Dockerfile
      args:
         - SERVER_ADDR=$SERVICE_ADDR
    ports:
      - "$SERVER_PORT:80"

  redis:
    image: redis
