version: "3"
services:
  backend:
    container_name: annotation-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3002:3002" # Web Server
      - "3001:3001" # GRPC Proxy Server
      - "3000:3000" # GRPC Server
      - "8000:8000"
      - "8002:8002"
    environment:
      - SCM_DIR=/root/scm_result
      - PROD_MODE=1
      - SERVICE_PORT=3000
      - ATOM_SERVER=localhost
      - ATOM_ID=prod-atom
      - SERVICE_ADDR=$SERVICE_ADDR
      - RESULT_DIR=/root/result
    working_dir: /root/annotation_service/
    command: bash -c "circusd --log-level debug circus-dev.ini"

    volumes:
     - $HOME/.mozi/prod:/opt
     - $DATASET:/root/annotation_service/datasets
     - $RESULT_DIR:/root/result
  frontend:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        - GRPC_ADDR=$GRPC_ADDR
        - RESULT_ADDR=$RESULT_ADDR
    ports:
      - "3003:80" #annotation ui port