version: 2

jobs:
    build:
        machine: true
        environment:
            - container: annotation-service

        working_directory: ~/mozi_annotation_service
        steps:
            - checkout
            - run:
                  name: Pull Submodules
                  command: |
                    git submodule init
                    git submodule update --remote
            - run:
                  name: Start the containers
                  command: |
                    export SERVER_PORT=3200
                    export SERVICE_ADDR=http://46.4.115.181
                    docker-compose up -d

    deploy:
        machine: true
        steps:
            - add_ssh_keys:
                  fingerprints:
                    - "69:b8:f5:ab:d4:05:bb:02:09:57:9e:7f:0c:e1:74:81"        
            - run:
                  name: Deploy over SSH
                  command: |
                      ssh $SSH_USER@$SERVER bash << EOF
                        cd /opt/snet
                        if [ ! -d "annotation-service" ]; then
                            # clone the repo if it doesn't exist
                            git clone --recursive https://github.com/MOZI-AI/annotation-service.git
                        else
                            git checkout -- .
                            git pull
                        fi
                        export SERVER_PORT=3200
                        export SERVICE_ADDR=http://46.4.115.181
                        cd annotation-service;
                        docker-compose stop; # stop the containers if they are runnning
                        docker-compose build;
                        docker-compose up -d;
                      EOF
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
