version: 2

jobs:
    deploy:
        machine: true
        steps:
            - add_ssh_keys:
                  fingerprints:
                    - "a7:ad:aa:89:31:ab:4e:fd:89:c4:b4:7a:df:bb:e0:c41"   
            - run:
                  name: Deploy over SSH
                  command: |
                      ssh $SSH_USER@$SERVER bash << EOF
                        cd /opt/snet
                        if [ ! -d "annotation-service" ]; then
                            # clone the repo if it doesn't exist
                            git clone --recursive https://github.com/MOZI-AI/annotation-service.git
                        fi
                        cd annotation-service
                        git checkout -- .
                        git pull
                        git submodule init
                        git submodule update --remote
                        docker-compose stop; # stop the containers if they are runnning
                        sed -ri 's/^(\s*)(-\sPROD_MODE=0\s*$)/\1- PROD_MODE=1/' docker-compose.yml #switch to Production Mode
                        source ~/.bashrc
                        docker-compose up -d --build;
                      EOF
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - deploy