version: 2

jobs:
    deploy:
        machine: true
        steps:
            - add_ssh_keys:
                  fingerprints:
                    - "69:b8:f5:ab:d4:05:bb:02:09:57:9e:7f:0c:e1:74:81"        
            - run:
                  name: Deploy over SSH
                  command: |
                      ssh $SSH_USER@$SERVER bash << EOF
                        cd /opt/snet
                        if [ ! -d "annotation-service" ]; then
                            # clone the repo if it doesn't exist
                            git clone --recursive https://github.com/MOZI-AI/annotation-service.git
                        else
                            git checkout -- .
                            git pull
                        fi
                        export SERVER_PORT=3200
                        export SERVICE_ADDR=mozi.ai
                        export DATASET=/opt/snet/datasets
                        export RESULT_DIR=/opt/snet/results
                        cd annotation-service;
                        docker-compose stop; # stop the containers if they are runnning
                        docker-compose build;
                        docker-compose up -d;
                      EOF
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - deploy