version: 2

jobs:
    deploy:
        machine: true
        steps:
            - add_ssh_keys:
                  fingerprints:
                    - "69:b8:f5:ab:d4:05:bb:02:09:57:9e:7f:0c:e1:74:81"        
            - run:
                  name: Deploy over SSH
                  command: |
                      ssh $SSH_USER@$SERVER bash << EOF
                        cd /opt/snet
                        if [ ! -d "annotation-service" ]; then
                            # clone the repo if it doesn't exist
                            git clone --recursive https://github.com/MOZI-AI/annotation-service.git
                            cd annotation-service
                        else
                            cd annotation-service
                            git checkout -- .
                            git pull
                            git submodule init
                            git submodule update --remote
                        fi
                        export GRPC_ADDR=https://annotation.mozi.ai/grpc
                        export RESULT_ADDR=https://annotation.mozi.ai/web
                        export SERVICE_ADDR=mozi.ai
                        export DATASET=/var/www/datasets
                        export RESULT_DIR=/opt/snet/annotation-result
                        cd annotation-service;
                        docker-compose stop; # stop the containers if they are runnning
                        sed -ri 's/^(\s*)(-\sPROD_MODE=0\s*$)/\1- PROD_MODE=1/' docker-compose.yml #switch to Production Mode
                        docker-compose up -d --build;
                      EOF
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - deploy